model_name: tcn
learning_rate: 0.0001
batch_size: 40
epoch: 7
sequence_length: 4
workers: 4

out_features: 7  
mstcn_causal_conv: True
mstcn_layers: 8
mstcn_f_maps: 32
mstcn_f_dim: 2048
mstcn_stages: 2

train_feature_path: /home/ubuntu/disk1/Even/even/SurgicalPhaseFramework/result/feature/resnet50/resnet50_train.pkl
test_feature_path: /home/ubuntu/disk1/Even/even/SurgicalPhaseFramework/result/feature/resnet50/resnet50_test.pkl
eval_model_path: ./result/model/tcn/6-0.8793.model