model_name: TMR
learning_rate: 0.0001
batch_size: 40
epoch: 3
sequence_length: 4
workers: 4

is_time_conv: True
LFB_length: 30

train_feature_path: /home/ubuntu/disk1/Even/even/SurgicalPhaseFramework/result/feature/resnet_lstm/g_LFB_train_st.pkl
val_feature_path: /home/ubuntu/disk1/Even/even/SurgicalPhaseFramework/result/feature/resnet_lstm/g_LFB_test_st.pkl
eval_model_path: /home/ubuntu/disk1/Even/even/SurgicalPhaseFramework/result/model/TMR/0-0.8038.model